//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamageMeter.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DamageMeter.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the application?.
        /// </summary>
        public static string App_Do_you_want_to_update {
            get {
                return ResourceManager.GetString("App_Do_you_want_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact update server, try again later, additional data available in error.log.
        /// </summary>
        public static string App_Unable_to_contact_update_server {
            get {
                return ResourceManager.GetString("App_Unable_to_contact_update_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string App_Update_Available {
            get {
                return ResourceManager.GetString("App_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chained.
        /// </summary>
        public static string Chained {
            get {
                return ResourceManager.GetString("Chained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage done.
        /// </summary>
        public static string Damage_done {
            get {
                return ResourceManager.GetString("Damage_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOT.
        /// </summary>
        public static string DOT {
            get {
                return ResourceManager.GetString("DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight Duration.
        /// </summary>
        public static string Fight_Duration {
            get {
                return ResourceManager.GetString("Fight_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual dps.
        /// </summary>
        public static string Individual_dps {
            get {
                return ResourceManager.GetString("Individual_dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss + Adds.
        /// </summary>
        public static string MainWindow_Boss_Adds {
            get {
                return ResourceManager.GetString("MainWindow_Boss_Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Shinra Meter V.
        /// </summary>
        public static string MainWindow_Close_Shinra_Meter_V {
            get {
                return ResourceManager.GetString("MainWindow_Close_Shinra_Meter_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the application?.
        /// </summary>
        public static string MainWindow_Do_you_want_to_close_the_application {
            get {
                return ResourceManager.GetString("MainWindow_Do_you_want_to_close_the_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An fatal error has be found, please see the error.log file for more information..
        /// </summary>
        public static string MainWindow_Fatal_error {
            get {
                return ResourceManager.GetString("MainWindow_Fatal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only boss.
        /// </summary>
        public static string MainWindow_Only_boss {
            get {
                return ResourceManager.GetString("MainWindow_Only_boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /s.
        /// </summary>
        public static string PerSecond {
            get {
                return ResourceManager.GetString("PerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string SystemTray_Action {
            get {
                return ResourceManager.GetString("SystemTray_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoexport to Excel.
        /// </summary>
        public static string SystemTray_Autoexport_to_Excel {
            get {
                return ResourceManager.GetString("SystemTray_Autoexport_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before crash.
        /// </summary>
        public static string SystemTray_before_crash {
            get {
                return ResourceManager.GetString("SystemTray_before_crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click throu.
        /// </summary>
        public static string SystemTray_Click_throu {
            get {
                return ResourceManager.GetString("SystemTray_Click_throu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string SystemTray_Config {
            get {
                return ResourceManager.GetString("SystemTray_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count only bosses.
        /// </summary>
        public static string SystemTray_Count_only_bosses {
            get {
                return ResourceManager.GetString("SystemTray_Count_only_bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count only party members.
        /// </summary>
        public static string SystemTray_Count_only_party_members {
            get {
                return ResourceManager.GetString("SystemTray_Count_only_party_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect bosses by HP bar (ignore db).
        /// </summary>
        public static string SystemTray_Detect_bosses_by_HP_bar {
            get {
                return ResourceManager.GetString("SystemTray_Detect_bosses_by_HP_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string SystemTray_Discord {
            get {
                return ResourceManager.GetString("SystemTray_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current to Excel.
        /// </summary>
        public static string SystemTray_Export_current_to_Excel {
            get {
                return ResourceManager.GetString("SystemTray_Export_current_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible when no stats.
        /// </summary>
        public static string SystemTray_Invisible_when_no_stats {
            get {
                return ResourceManager.GetString("SystemTray_Invisible_when_no_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string SystemTray_Links {
            get {
                return ResourceManager.GetString("SystemTray_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packets waiting to be processed.
        /// </summary>
        public static string SystemTray_Packet_waiting {
            get {
                return ResourceManager.GetString("SystemTray_Packet_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch note.
        /// </summary>
        public static string SystemTray_Patch_note {
            get {
                return ResourceManager.GetString("SystemTray_Patch_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance information.
        /// </summary>
        public static string SystemTray_Performance_information {
            get {
                return ResourceManager.GetString("SystemTray_Performance_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string SystemTray_Report_issue {
            get {
                return ResourceManager.GetString("SystemTray_Report_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show always.
        /// </summary>
        public static string SystemTray_Show_always {
            get {
                return ResourceManager.GetString("SystemTray_Show_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site export.
        /// </summary>
        public static string SystemTray_Site_export {
            get {
                return ResourceManager.GetString("SystemTray_Site_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay topmost.
        /// </summary>
        public static string SystemTray_Stay_topmost {
            get {
                return ResourceManager.GetString("SystemTray_Stay_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeraDps.io.
        /// </summary>
        public static string SystemTray_TeraDps_io {
            get {
                return ResourceManager.GetString("SystemTray_TeraDps_io", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string SystemTray_Wiki {
            get {
                return ResourceManager.GetString("SystemTray_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Skill.
        /// </summary>
        public static string Unknown_Skill {
            get {
                return ResourceManager.GetString("Unknown_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
