//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lang {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LP() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lang.LP", typeof(LP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add DPS server.
        /// </summary>
        public static string AddDpsServer {
            get {
                return ResourceManager.GetString("AddDpsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggro.
        /// </summary>
        public static string Aggro {
            get {
                return ResourceManager.GetString("Aggro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggro time.
        /// </summary>
        public static string Aggro_Time {
            get {
                return ResourceManager.GetString("Aggro_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Time holding boss aggro&quot;.
        /// </summary>
        public static string Aggro_Time_Tooltip {
            get {
                return ResourceManager.GetString("Aggro_Time_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggro take count.
        /// </summary>
        public static string Aggro_Tooltip {
            get {
                return ResourceManager.GetString("Aggro_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alliance color.
        /// </summary>
        public static string AllianceColor {
            get {
                return ResourceManager.GetString("AllianceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allowed area url.
        /// </summary>
        public static string AllowedAreaUrl {
            get {
                return ResourceManager.GetString("AllowedAreaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  probably is already in use..
        /// </summary>
        public static string AlreadyInUse {
            get {
                return ResourceManager.GetString("AlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to update the application?.
        /// </summary>
        public static string App_Do_you_want_to_update {
            get {
                return ResourceManager.GetString("App_Do_you_want_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to contact update server, try again later, additional data available in error.log.
        /// </summary>
        public static string App_Unable_to_contact_update_server {
            get {
                return ResourceManager.GetString("App_Unable_to_contact_update_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update Available.
        /// </summary>
        public static string App_Update_Available {
            get {
                return ResourceManager.GetString("App_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a apply to your party.
        /// </summary>
        public static string ApplyToYourParty {
            get {
                return ResourceManager.GetString("ApplyToYourParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Archer.
        /// </summary>
        public static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Area color.
        /// </summary>
        public static string AreaColor {
            get {
                return ResourceManager.GetString("AreaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Auth Token.
        /// </summary>
        public static string AuthToken {
            get {
                return ResourceManager.GetString("AuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avg.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avg crit.
        /// </summary>
        public static string AverageCrit {
            get {
                return ResourceManager.GetString("AverageCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avg DPS.
        /// </summary>
        public static string AvgDPS {
            get {
                return ResourceManager.GetString("AvgDPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avg white.
        /// </summary>
        public static string AvgWhite {
            get {
                return ResourceManager.GetString("AvgWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bad server url.
        /// </summary>
        public static string Bad_server_url {
            get {
                return ResourceManager.GetString("Bad_server_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Berserker.
        /// </summary>
        public static string Berserker {
            get {
                return ResourceManager.GetString("Berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blur player names.
        /// </summary>
        public static string Blur_player_names {
            get {
                return ResourceManager.GetString("Blur_player_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Boss.
        /// </summary>
        public static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Boss HP.
        /// </summary>
        public static string BossHP {
            get {
                return ResourceManager.GetString("BossHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Brawler.
        /// </summary>
        public static string Brawler {
            get {
                return ResourceManager.GetString("Brawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Buff.
        /// </summary>
        public static string Buff {
            get {
                return ResourceManager.GetString("Buff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chained.
        /// </summary>
        public static string Chained {
            get {
                return ResourceManager.GetString("Chained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a s CMA DPS.
        /// </summary>
        public static string CMADPS {
            get {
                return ResourceManager.GetString("CMADPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Combat ready check.
        /// </summary>
        public static string CombatReadyCheck {
            get {
                return ResourceManager.GetString("CombatReadyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact try.
        /// </summary>
        public static string ContactTry {
            get {
                return ResourceManager.GetString("ContactTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy &quot;/inspect Name&quot; on party apply request.
        /// </summary>
        public static string CopyInspect {
            get {
                return ResourceManager.GetString("CopyInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skill Сasts.
        /// </summary>
        public static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Crit Dmg.
        /// </summary>
        public static string CritDamagePercent {
            get {
                return ResourceManager.GetString("CritDamagePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Crit.
        /// </summary>
        public static string CritPercent {
            get {
                return ResourceManager.GetString("CritPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crits.
        /// </summary>
        public static string Crits {
            get {
                return ResourceManager.GetString("Crits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Damage done.
        /// </summary>
        public static string Damage_done {
            get {
                return ResourceManager.GetString("Damage_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Dmg.
        /// </summary>
        public static string DamagePercent {
            get {
                return ResourceManager.GetString("DamagePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dmg taken.
        /// </summary>
        public static string DamgeTaken {
            get {
                return ResourceManager.GetString("DamgeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Death time.
        /// </summary>
        public static string Death_Time {
            get {
                return ResourceManager.GetString("Death_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Time spent on the floor&quot;.
        /// </summary>
        public static string Death_Time_Tooltip {
            get {
                return ResourceManager.GetString("Death_Time_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deaths count.
        /// </summary>
        public static string Deaths_Tooltip {
            get {
                return ResourceManager.GetString("Deaths_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delay to wait when pasting.
        /// </summary>
        public static string DelayToWaitPasting {
            get {
                return ResourceManager.GetString("DelayToWaitPasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disable party events.
        /// </summary>
        public static string DisablePartyEvents {
            get {
                return ResourceManager.GetString("DisablePartyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Display only boss hit by meter user.
        /// </summary>
        public static string Display_only_boss_hit_by_meter_user {
            get {
                return ResourceManager.GetString("Display_only_boss_hit_by_meter_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer based on aggro.
        /// </summary>
        public static string Display_timer_aggro_or_firsthit {
            get {
                return ResourceManager.GetString("Display_timer_aggro_or_firsthit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DOT.
        /// </summary>
        public static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dps.
        /// </summary>
        public static string Dps {
            get {
                return ResourceManager.GetString("Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DPS upload url.
        /// </summary>
        public static string DpsUploadUrl {
            get {
                return ResourceManager.GetString("DpsUploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Eff Time.
        /// </summary>
        public static string EffectTime {
            get {
                return ResourceManager.GetString("EffectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emotes color.
        /// </summary>
        public static string EmotesColor {
            get {
                return ResourceManager.GetString("EmotesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable chat and notification functions.
        /// </summary>
        public static string EnableChat {
            get {
                return ResourceManager.GetString("EnableChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable overlay.
        /// </summary>
        public static string EnableOverlay {
            get {
                return ResourceManager.GetString("EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enabled.
        /// </summary>
        public static string EnableRealtimeGraph {
            get {
                return ResourceManager.GetString("EnableRealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable discord&apos;s Rich Presence.
        /// </summary>
        public static string EnableRp {
            get {
                return ResourceManager.GetString("EnableRp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enrage.
        /// </summary>
        public static string Enrage {
            get {
                return ResourceManager.GetString("Enrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;.
        /// </summary>
        public static string events_archer {
            get {
                return ResourceManager.GetString("events_archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///  &lt;!-- Unleash ubreakable --&gt;
        ///    &lt;abnormality ingame=&quot;true&quot; trigger=&quot;Ending&quot; target=&quot;Self&quot; remaining_seconds_before_trigger=&quot;3&quot; rewarn_timeout_seconds=&quot;2&quot;&gt;
        ///        &lt;abnormalities&gt;
        ///            &lt;abnormality&gt;401705&lt;/abnormality&gt;
        ///        &lt;/abnormalities&gt;
        ///        &lt;actions&gt;
        ///            &lt;notify&gt;
        ///                &lt;text_to_speech text=&quot;Die Die Die&quot; voice_gender=&quot;Male&quot; voice_age=&quot;Adult&quot; voice_position=&quot;0&quot; volume=&quot;30&quot; rate=&quot;1&quot;/&gt;
        ///            &lt;/notify&gt;
        ///    [stringa troncata]&quot;;.
        /// </summary>
        public static string events_berserker {
            get {
                return ResourceManager.GetString("events_berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;	
        ///	&lt;!-- Endurance debuff  --&gt;
        ///	&lt;abnormality active=&quot;false&quot; ingame=&quot;true&quot; rewarn_timeout_seconds=&quot;5&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Boss&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;10153140&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200300&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200301&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200302&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot; [stringa troncata]&quot;;.
        /// </summary>
        public static string events_brawler {
            get {
                return ResourceManager.GetString("events_brawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///
        ///	&lt;!-- Adrenaline Rush --&gt;
        ///	&lt;abnormality active=&quot;true&quot; ingame=&quot;true&quot; trigger=&quot;Added&quot; target=&quot;Self&quot; ignore_classes=&quot;Mystic,Priest&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;200701&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200700&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;text_to_speech text=&quot;{abnormality_name}&quot; voice_gender=&quot;Female&quot; voice_age=&quot;Adult&quot;  voice_position=&quot;0&quot; volume=&quot;80&quot; rate=&quot;+3&quot;/&gt;
        ///			&lt;/notify&gt;
        ///		&lt;/actions&gt;
        ///	&lt;/abnormality&gt;
        ///	
        ///	&lt;!-- P [stringa troncata]&quot;;.
        /// </summary>
        public static string events_common {
            get {
                return ResourceManager.GetString("events_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///		
        ///&lt;/events&gt;.
        /// </summary>
        public static string events_gunner {
            get {
                return ResourceManager.GetString("events_gunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;	
        ///	&lt;!-- Endurance debuff --&gt;
        ///	&lt;abnormality active=&quot;true&quot; ingame=&quot;true&quot; rewarn_timeout_seconds=&quot;5&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Boss&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;200300&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200301&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200302&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{abnormality_name}&quot; display_time=&quot;3000&quot; / [stringa troncata]&quot;;.
        /// </summary>
        public static string events_lancer {
            get {
                return ResourceManager.GetString("events_lancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///
        ///	&lt;!-- Unleash berserker --&gt;
        ///	&lt;abnormality ingame=&quot;true&quot; trigger=&quot;Added&quot; target=&quot;Party&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;401705&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{abnormality_name}&quot; display_time=&quot;1000&quot; /&gt;
        ///				&lt;text_to_speech text=&quot;{abnormality_name}&quot; voice_gender=&quot;Male&quot; voice_age=&quot;Adult&quot;  voice_position=&quot;0&quot; volume=&quot;30&quot; rate=&quot;1&quot;/&gt;
        ///			&lt;/notify&gt;
        ///		&lt;/actions&gt;
        ///	&lt;/abnor [stringa troncata]&quot;;.
        /// </summary>
        public static string events_mystic {
            get {
                return ResourceManager.GetString("events_mystic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///	&lt;!-- Focus --&gt;
        ///	&lt;abnormality active=&quot;true&quot; rewarn_timeout_seconds=&quot;3&quot; ingame=&quot;true&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Self&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;10154030&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;text_to_speech text=&quot;Focus&quot; voice_gender=&quot;Female&quot; voice_age=&quot;Adult&quot;  voice_position=&quot;0&quot; volume=&quot;80&quot; rate=&quot;+3&quot;/&gt;
        ///			&lt;/notify&gt;
        ///		&lt;/actions&gt;
        ///	&lt;/abnormality&gt;
        ///&lt;/events&gt;.
        /// </summary>
        public static string events_ninja {
            get {
                return ResourceManager.GetString("events_ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///	
        ///	
        ///	&lt;!-- Unleash berserker --&gt;
        ///	&lt;abnormality ingame=&quot;true&quot; trigger=&quot;Added&quot; target=&quot;Party&quot; ignore_classes=&quot;Berserker&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;401705&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;actions&gt;
        ///			&lt;notify&gt;
        ///				&lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{abnormality_name}&quot; display_time=&quot;1000&quot; /&gt;
        ///				&lt;text_to_speech text=&quot;{abnormality_name}&quot; voice_gender=&quot;Male&quot; voice_age=&quot;Adult&quot; voice_position=&quot;0&quot; volume=&quot;30&quot; rate=&quot;1&quot;/&gt;
        ///			&lt;/ [stringa troncata]&quot;;.
        /// </summary>
        public static string events_priest {
            get {
                return ResourceManager.GetString("events_priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;.
        /// </summary>
        public static string events_reaper {
            get {
                return ResourceManager.GetString("events_reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///  &lt;!-- Notifies for missing overpower buff--&gt;
        ///    &lt;abnormality ingame=&quot;true&quot; remaining_seconds_before_trigger=&quot;10&quot; rewarn_timeout_seconds=&quot;3&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;Self&quot;&gt;
        ///        &lt;abnormalities&gt;
        ///            &lt;abnormality&gt;300330&lt;/abnormality&gt;
        ///        &lt;/abnormalities&gt;
        ///        &lt;actions&gt;
        ///            &lt;notify&gt;
        ///                &lt;balloon title_text=&quot;{abnormality_name}&quot; body_text=&quot;{player_name} {time_left}&quot; display_time=&quot;3000&quot; /&gt;
        ///          [stringa troncata]&quot;;.
        /// </summary>
        public static string events_slayer {
            get {
                return ResourceManager.GetString("events_slayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;.
        /// </summary>
        public static string events_sorcerer {
            get {
                return ResourceManager.GetString("events_sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///&lt;/events&gt;.
        /// </summary>
        public static string events_valkyrie {
            get {
                return ResourceManager.GetString("events_valkyrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;events&gt;
        ///	
        ///	&lt;!-- Endurance debuff --&gt;
        ///	&lt;abnormality active=&quot;false&quot; ingame=&quot;true&quot; rewarn_timeout_seconds=&quot;5&quot; remaining_seconds_before_trigger=&quot;0&quot; trigger=&quot;MissingDuringFight&quot; target=&quot;MyBoss&quot;&gt;
        ///		&lt;abnormalities&gt;
        ///			&lt;abnormality&gt;101200&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;101220&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200300&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200301&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;200302&lt;/abnormality&gt;
        ///			&lt;abnormality&gt;10153140&lt;/abnormality&gt;
        ///		&lt;/abnormalities&gt;
        ///		&lt;a [stringa troncata]&quot;;.
        /// </summary>
        public static string events_warrior {
            get {
                return ResourceManager.GetString("events_warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export packets logs.
        /// </summary>
        public static string ExportPacketLogs {
            get {
                return ResourceManager.GetString("ExportPacketLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fight.
        /// </summary>
        public static string Fight {
            get {
                return ResourceManager.GetString("Fight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fight Duration.
        /// </summary>
        public static string Fight_Duration {
            get {
                return ResourceManager.GetString("Fight_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Fight.
        /// </summary>
        public static string FightPercent {
            get {
                return ResourceManager.GetString("FightPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Format paste string.
        /// </summary>
        public static string FormatPasteString {
            get {
                return ResourceManager.GetString("FormatPasteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Front.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a General color.
        /// </summary>
        public static string GeneralColor {
            get {
                return ResourceManager.GetString("GeneralColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Glyph upload url.
        /// </summary>
        public static string GlyphUploadURL {
            get {
                return ResourceManager.GetString("GlyphUploadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Group color.
        /// </summary>
        public static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Guild color.
        /// </summary>
        public static string GuildColor {
            get {
                return ResourceManager.GetString("GuildColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gunner.
        /// </summary>
        public static string Gunner {
            get {
                return ResourceManager.GetString("Gunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Heal.
        /// </summary>
        public static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Heal Crit %.
        /// </summary>
        public static string HealCritPercent {
            get {
                return ResourceManager.GetString("HealCritPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hits.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hits taken.
        /// </summary>
        public static string HitsTaken {
            get {
                return ResourceManager.GetString("HitsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HOT.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hit/m.
        /// </summary>
        public static string HPM {
            get {
                return ResourceManager.GetString("HPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle reset timeout in sec (0=disable).
        /// </summary>
        public static string IdleResetTimeout {
            get {
                return ResourceManager.GetString("IdleResetTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Individual dps.
        /// </summary>
        public static string Individual_dps {
            get {
                return ResourceManager.GetString("Individual_dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a JoyOfPartying 100%.
        /// </summary>
        public static string JoyOfPartying {
            get {
                return ResourceManager.GetString("JoyOfPartying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lancer.
        /// </summary>
        public static string Lancer {
            get {
                return ResourceManager.GetString("Lancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lvl.
        /// </summary>
        public static string Lvl {
            get {
                return ResourceManager.GetString("Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Boss + Adds.
        /// </summary>
        public static string MainWindow_Boss_Adds {
            get {
                return ResourceManager.GetString("MainWindow_Boss_Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close Shinra Meter V.
        /// </summary>
        public static string MainWindow_Close_Shinra_Meter_V {
            get {
                return ResourceManager.GetString("MainWindow_Close_Shinra_Meter_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to close the application?.
        /// </summary>
        public static string MainWindow_Do_you_want_to_close_the_application {
            get {
                return ResourceManager.GetString("MainWindow_Do_you_want_to_close_the_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An fatal error has be found, please see the error.log file for more information..
        /// </summary>
        public static string MainWindow_Fatal_error {
            get {
                return ResourceManager.GetString("MainWindow_Fatal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Only boss.
        /// </summary>
        public static string MainWindow_Only_boss {
            get {
                return ResourceManager.GetString("MainWindow_Only_boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mana.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max crit.
        /// </summary>
        public static string MaxCrit {
            get {
                return ResourceManager.GetString("MaxCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TTS max size.
        /// </summary>
        public static string MaxTTSSize {
            get {
                return ResourceManager.GetString("MaxTTSSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max white.
        /// </summary>
        public static string MaxWhite {
            get {
                return ResourceManager.GetString("MaxWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Min Crit.
        /// </summary>
        public static string MinCrit {
            get {
                return ResourceManager.GetString("MinCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MOT.
        /// </summary>
        public static string Mot {
            get {
                return ResourceManager.GetString("Mot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mute sound.
        /// </summary>
        public static string MuteSound {
            get {
                return ResourceManager.GetString("MuteSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mystic.
        /// </summary>
        public static string Mystic {
            get {
                return ResourceManager.GetString("Mystic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ninja.
        /// </summary>
        public static string Ninja {
            get {
                return ResourceManager.GetString("Ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No active quest at the moment.
        /// </summary>
        public static string No_active_quest {
            get {
                return ResourceManager.GetString("No_active_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disable abnormality icons under HP bar.
        /// </summary>
        public static string NoAbnormalsInHUD {
            get {
                return ResourceManager.GetString("NoAbnormalsInHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CrystalBind missing.
        /// </summary>
        public static string NoCrystalBind {
            get {
                return ResourceManager.GetString("NoCrystalBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disable ingame chat paste.
        /// </summary>
        public static string NoPaste {
            get {
                return ResourceManager.GetString("NoPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notify about CrystalBinds..
        /// </summary>
        public static string NotifyCB {
            get {
                return ResourceManager.GetString("NotifyCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number of players displayed.
        /// </summary>
        public static string NumberPlayersDisplayed {
            get {
                return ResourceManager.GetString("NumberPlayersDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offered price.
        /// </summary>
        public static string OfferedPrice {
            get {
                return ResourceManager.GetString("OfferedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open chat box.
        /// </summary>
        public static string OpenChatBox {
            get {
                return ResourceManager.GetString("OpenChatBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Party invite.
        /// </summary>
        public static string PartyInvite {
            get {
                return ResourceManager.GetString("PartyInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Party matching success.
        /// </summary>
        public static string PartyMatchingSuccess {
            get {
                return ResourceManager.GetString("PartyMatchingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a /s.
        /// </summary>
        public static string PerSecond {
            get {
                return ResourceManager.GetString("PerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pet.
        /// </summary>
        public static string Pet {
            get {
                return ResourceManager.GetString("Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Popup stay active for X ms.
        /// </summary>
        public static string PopupStayActiveForXms {
            get {
                return ResourceManager.GetString("PopupStayActiveForXms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Priest.
        /// </summary>
        public static string Priest {
            get {
                return ResourceManager.GetString("Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Private channel color.
        /// </summary>
        public static string PrivateChannelColor {
            get {
                return ResourceManager.GetString("PrivateChannelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quests done status: .
        /// </summary>
        public static string Quests_status {
            get {
                return ResourceManager.GetString("Quests_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Raid color.
        /// </summary>
        public static string RaidColor {
            get {
                return ResourceManager.GetString("RaidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CMA seconds.
        /// </summary>
        public static string RealtimeGraphCmaSeconds {
            get {
                return ResourceManager.GetString("RealtimeGraphCmaSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Displayed interval.
        /// </summary>
        public static string RealtimeGraphDisplayedInterval {
            get {
                return ResourceManager.GetString("RealtimeGraphDisplayedInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reaper.
        /// </summary>
        public static string Reaper {
            get {
                return ResourceManager.GetString("Reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Couldn’t register the hot key..
        /// </summary>
        public static string RegisterHotKeyError {
            get {
                return ResourceManager.GetString("RegisterHotKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove DPS server.
        /// </summary>
        public static string RemoveDpsServer {
            get {
                return ResourceManager.GetString("RemoveDpsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Tera alt+enter hotkey.
        /// </summary>
        public static string RemoveTeraAltEnterHotkey {
            get {
                return ResourceManager.GetString("RemoveTeraAltEnterHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show character.
        /// </summary>
        public static string RichPresenceShowCharacter {
            get {
                return ResourceManager.GetString("RichPresenceShowCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show location.
        /// </summary>
        public static string RichPresenceShowLocation {
            get {
                return ResourceManager.GetString("RichPresenceShowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show party.
        /// </summary>
        public static string RichPresenceShowParty {
            get {
                return ResourceManager.GetString("RichPresenceShowParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show status.
        /// </summary>
        public static string RichPresenceShowStatus {
            get {
                return ResourceManager.GetString("RichPresenceShowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lvl.
        /// </summary>
        public static string RpLevel {
            get {
                return ResourceManager.GetString("RpLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Various.
        /// </summary>
        public static string RpMultipleEnemies {
            get {
                return ResourceManager.GetString("RpMultipleEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BG Queue.
        /// </summary>
        public static string RpPartyBg {
            get {
                return ResourceManager.GetString("RpPartyBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In party.
        /// </summary>
        public static string RpPartyParty {
            get {
                return ResourceManager.GetString("RpPartyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IMS.
        /// </summary>
        public static string RpPartyQueue {
            get {
                return ResourceManager.GetString("RpPartyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In raid.
        /// </summary>
        public static string RpPartyRaid {
            get {
                return ResourceManager.GetString("RpPartyRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Solo.
        /// </summary>
        public static string RpPartySolo {
            get {
                return ResourceManager.GetString("RpPartySolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In battleground matching.
        /// </summary>
        public static string RpStatusBattlegroundMatch {
            get {
                return ResourceManager.GetString("RpStatusBattlegroundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Character selection.
        /// </summary>
        public static string RpStatusCharSelect {
            get {
                return ResourceManager.GetString("RpStatusCharSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In dungeon matching.
        /// </summary>
        public static string RpStatusDungeonMatch {
            get {
                return ResourceManager.GetString("RpStatusDungeonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fight.
        /// </summary>
        public static string RpStatusFight {
            get {
                return ResourceManager.GetString("RpStatusFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle.
        /// </summary>
        public static string RpStatusIdle {
            get {
                return ResourceManager.GetString("RpStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LFG.
        /// </summary>
        public static string RpStatusLfg {
            get {
                return ResourceManager.GetString("RpStatusLfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Playing.
        /// </summary>
        public static string RpStatusPlaying {
            get {
                return ResourceManager.GetString("RpStatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Say color.
        /// </summary>
        public static string SayColor {
            get {
                return ResourceManager.GetString("SayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a s.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seller price.
        /// </summary>
        public static string SellerPrice {
            get {
                return ResourceManager.GetString("SellerPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ###########################################################
        ///# Add additional servers in this file (needed only for
        ///# VPN/Proxy that is not supported out-of-box)
        ///#
        ///# Format must follow the format IP Region ServerName
        ///#
        ///# Example:
        ///# 111.22.33.44 NA VPN Server 1
        ///#
        ///# Current possible regions: EU, NA, RU, KR, KR-PTS, TW, THA, JP, JP-C
        ///#
        ///# Lines starting with &apos;#&apos; are ignored
        ///# Place servers below the next line
        ///###########################################################.
        /// </summary>
        public static string ServerOverrides {
            get {
                return ResourceManager.GetString("ServerOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show common_afk events ingame.
        /// </summary>
        public static string ShowAfkEventsIngame {
            get {
                return ResourceManager.GetString("ShowAfkEventsIngame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Boss HP Bar.
        /// </summary>
        public static string ShowBossGage {
            get {
                return ResourceManager.GetString("ShowBossGage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show self on top position in UI.
        /// </summary>
        public static string ShowSelfOnTop {
            get {
                return ResourceManager.GetString("ShowSelfOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Side.
        /// </summary>
        public static string Side {
            get {
                return ResourceManager.GetString("Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SkillDealt.
        /// </summary>
        public static string SkillDealt {
            get {
                return ResourceManager.GetString("SkillDealt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skill name.
        /// </summary>
        public static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SkillReceived.
        /// </summary>
        public static string SkillReceived {
            get {
                return ResourceManager.GetString("SkillReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Slayer.
        /// </summary>
        public static string Slayer {
            get {
                return ResourceManager.GetString("Slayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Slaying.
        /// </summary>
        public static string Slaying {
            get {
                return ResourceManager.GetString("Slaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &apos;Slaying&apos; crystal is working (if equipped) when player in this state..
        /// </summary>
        public static string SlayingTooltip {
            get {
                return ResourceManager.GetString("SlayingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorcerer.
        /// </summary>
        public static string Sorcerer {
            get {
                return ResourceManager.GetString("Sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Switch to another sound system.
        /// </summary>
        public static string SoundConsoleBeepFallback {
            get {
                return ResourceManager.GetString("SoundConsoleBeepFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound filename.
        /// </summary>
        public static string SoundFilename {
            get {
                return ResourceManager.GetString("SoundFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound stay active for X ms.
        /// </summary>
        public static string SoundStayActiveForXms {
            get {
                return ResourceManager.GetString("SoundStayActiveForXms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound volume.
        /// </summary>
        public static string SoundVolume {
            get {
                return ResourceManager.GetString("SoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Action.
        /// </summary>
        public static string SystemTray_Action {
            get {
                return ResourceManager.GetString("SystemTray_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autoexport to Excel.
        /// </summary>
        public static string SystemTray_Autoexport_to_Excel {
            get {
                return ResourceManager.GetString("SystemTray_Autoexport_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a before crash.
        /// </summary>
        public static string SystemTray_before_crash {
            get {
                return ResourceManager.GetString("SystemTray_before_crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Click throu.
        /// </summary>
        public static string SystemTray_Click_throu {
            get {
                return ResourceManager.GetString("SystemTray_Click_throu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Config.
        /// </summary>
        public static string SystemTray_Config {
            get {
                return ResourceManager.GetString("SystemTray_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Count only bosses.
        /// </summary>
        public static string SystemTray_Count_only_bosses {
            get {
                return ResourceManager.GetString("SystemTray_Count_only_bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Count only party members.
        /// </summary>
        public static string SystemTray_Count_only_party_members {
            get {
                return ResourceManager.GetString("SystemTray_Count_only_party_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Detect bosses by HP bar (ignore db).
        /// </summary>
        public static string SystemTray_Detect_bosses_by_HP_bar {
            get {
                return ResourceManager.GetString("SystemTray_Detect_bosses_by_HP_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Discord.
        /// </summary>
        public static string SystemTray_Discord {
            get {
                return ResourceManager.GetString("SystemTray_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Excel: calc moving average DPS for X seconds.
        /// </summary>
        public static string SystemTray_ExcelCMADPSSeconds {
            get {
                return ResourceManager.GetString("SystemTray_ExcelCMADPSSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export current to Excel.
        /// </summary>
        public static string SystemTray_Export_current_to_Excel {
            get {
                return ResourceManager.GetString("SystemTray_Export_current_to_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export current to site.
        /// </summary>
        public static string SystemTray_Export_current_to_Site {
            get {
                return ResourceManager.GetString("SystemTray_Export_current_to_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invisible when no stats.
        /// </summary>
        public static string SystemTray_Invisible_when_no_stats {
            get {
                return ResourceManager.GetString("SystemTray_Invisible_when_no_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Links.
        /// </summary>
        public static string SystemTray_Links {
            get {
                return ResourceManager.GetString("SystemTray_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No server.
        /// </summary>
        public static string SystemTray_No_server {
            get {
                return ResourceManager.GetString("SystemTray_No_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Packets waiting to be processed.
        /// </summary>
        public static string SystemTray_Packet_waiting {
            get {
                return ResourceManager.GetString("SystemTray_Packet_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Patch note.
        /// </summary>
        public static string SystemTray_Patch_note {
            get {
                return ResourceManager.GetString("SystemTray_Patch_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Performance information.
        /// </summary>
        public static string SystemTray_Performance_information {
            get {
                return ResourceManager.GetString("SystemTray_Performance_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Report issue.
        /// </summary>
        public static string SystemTray_Report_issue {
            get {
                return ResourceManager.GetString("SystemTray_Report_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show always.
        /// </summary>
        public static string SystemTray_Show_always {
            get {
                return ResourceManager.GetString("SystemTray_Show_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show realtime graph.
        /// </summary>
        public static string SystemTray_ShowGraph {
            get {
                return ResourceManager.GetString("SystemTray_ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Site export.
        /// </summary>
        public static string SystemTray_Site_export {
            get {
                return ResourceManager.GetString("SystemTray_Site_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stay topmost.
        /// </summary>
        public static string SystemTray_Stay_topmost {
            get {
                return ResourceManager.GetString("SystemTray_Stay_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use npcap (requires restart).
        /// </summary>
        public static string SystemTray_Use_Npcap {
            get {
                return ResourceManager.GetString("SystemTray_Use_Npcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wiki.
        /// </summary>
        public static string SystemTray_Wiki {
            get {
                return ResourceManager.GetString("SystemTray_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Api error or timeout..
        /// </summary>
        public static string TeraDpsIoApiError {
            get {
                return ResourceManager.GetString("TeraDpsIoApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test sound.
        /// </summary>
        public static string TestSound {
            get {
                return ResourceManager.GetString("TestSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Time sync error.
        /// </summary>
        public static string Time_sync_error {
            get {
                return ResourceManager.GetString("Time_sync_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TOTAL.
        /// </summary>
        public static string TotalEncounter {
            get {
                return ResourceManager.GetString("TotalEncounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trading.
        /// </summary>
        public static string Trading {
            get {
                return ResourceManager.GetString("Trading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trading color.
        /// </summary>
        public static string TradingColor {
            get {
                return ResourceManager.GetString("TradingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Truncate TTS message.
        /// </summary>
        public static string TTSSizeExceededTruncate {
            get {
                return ResourceManager.GetString("TTSSizeExceededTruncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to get key from string.
        /// </summary>
        public static string Unable_to_get_key_from_string {
            get {
                return ResourceManager.GetString("Unable_to_get_key_from_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown client version, meter require update to continue working: .
        /// </summary>
        public static string Unknown_client_version {
            get {
                return ResourceManager.GetString("Unknown_client_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload glyph build.
        /// </summary>
        public static string UploadGlyphBuild {
            get {
                return ResourceManager.GetString("UploadGlyphBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paused by user.
        /// </summary>
        public static string UserPaused {
            get {
                return ResourceManager.GetString("UserPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valkyrie.
        /// </summary>
        public static string Valkyrie {
            get {
                return ResourceManager.GetString("Valkyrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vanguard credits are close to cap:.
        /// </summary>
        public static string VanguardCredits {
            get {
                return ResourceManager.GetString("VanguardCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting for map change or relog.
        /// </summary>
        public static string WaitingMapChange {
            get {
                return ResourceManager.GetString("WaitingMapChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warrior.
        /// </summary>
        public static string Warrior {
            get {
                return ResourceManager.GetString("Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Whisper.
        /// </summary>
        public static string Whisper {
            get {
                return ResourceManager.GetString("Whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Whisper color.
        /// </summary>
        public static string WhisperColor {
            get {
                return ResourceManager.GetString("WhisperColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your computer is too slow to use this DPS meter.
        ///Can&apos;t analyse all those packet in decent amount of time. 
        ///Reset and paused until map change or relog..
        /// </summary>
        public static string Your_computer_is_too_slow {
            get {
                return ResourceManager.GetString("Your_computer_is_too_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your hotkeys.xml file is invalid..
        /// </summary>
        public static string Your_hotkeys_xml_file_is_invalid {
            get {
                return ResourceManager.GetString("Your_hotkeys_xml_file_is_invalid", resourceCulture);
            }
        }
    }
}
